version: '3.8'

services:
  gat-fedppo:
    build: .
    container_name: gat-fedppo-rc1
    restart: unless-stopped
    
    # 资源限制
    deploy:
      resources:
        limits:
          cpus: '4.0'
          memory: 8G
        reservations:
          cpus: '2.0'
          memory: 4G
    
    # 环境变量
    environment:
      - PYTHONPATH=/app
      - TORCH_WEIGHTS_ONLY=False
      - CUDA_VISIBLE_DEVICES=0  # 如果有GPU
    
    # 卷挂载
    volumes:
      - ./logs:/app/logs
      - ./results:/app/results
    
    # 网络端口 (如果需要API服务)
    ports:
      - "8080:8080"
    
    # 健康检查
    healthcheck:
      test: ["CMD", "python3", "-c", "import torch; print('OK')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # 可选: 监控服务
  monitoring:
    image: prom/prometheus:latest
    container_name: gat-fedppo-monitoring
    restart: unless-stopped
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
      - gat-fedppo

# 网络配置
networks:
  default:
    driver: bridge

# 卷配置
volumes:
  logs:
    driver: local
  results:
    driver: local