gulfport:
  标准阶段:
    threshold: 0.44
  完整阶段:
    threshold: 0.33
baton_rouge:
  基础阶段:
    threshold: 0.45
  中级阶段:
    threshold: 0.5
  高级阶段:
    threshold: 0.34
new_orleans:
  基础阶段:
    threshold: 0.45
  中级阶段:
    threshold: 0.47
  高级阶段:
    threshold: 0.4
  专家阶段:
    threshold: 0.35
south_louisiana:
  标准阶段:
    threshold: 0.45
  完整阶段:
    threshold: 0.35
