# 基于Wilson下界计算的样本量配置
# 目标：让 Wilson 下界 ≥ (阈值 - 0.04)
# 当前置信区间松弛度: 0.04

ports:
  gulfport:
    standard_stage: 800    # 从600提升到800 (0.5075 vs 0.49)
    complete_stage: 1700   # 从400提升到1700 (0.3525 vs 0.37)
  
  new_orleans:
    advanced_stage: 800    # 从700提升到800，保持一致的统计置信度
  
  south_louisiana:
    advanced_stage: 800    # 从900调整到800，保持一致的统计置信度
  
  baton_rouge:
    intermediate_stage: 800  # 从1500调整到800，保持一致的统计置信度
    advanced_stage: 800      # 从1200调整到800，保持一致的统计置信度

# 计算依据：
# Gulfport标准: 0.5075胜率，阈值0.49，需要n≈600
# Gulfport完整: 0.3525胜率，阈值0.37，需要n≈1700  
# 统一提升到800样本量，保持一致的统计置信度
# 各港口阈值和胜率关系保持不变，但统计精度更一致 